### ISSUE TITLE
February 2024 meeting

### ISSUE THREAD

**Issue by jar398** [ocapn/ocapn#103]
**Date/time**: 2nd Tuesday [19:00 UTC on 13 February 2024](https://www.timeanddate.com/worldclock/converter.html?iso=20240213T190000&p1=239&p2=1440&p3=43&p4=1240).
**Location**: https://bbb.sfconservancy.org/b/chr-pm5-cl8-ctl
**Scribe**: volunteer sought
**Preliminary agenda**:
 * [Closed issues](https://github.com/ocapn/ocapn/issues?q=is%3Aissue+is%3Aclosed)  - discussion only if there are objections (none?)
 * Locators, addresses, and references #105 @kriskowal 
 * Review [open pull requests](https://github.com/ocapn/ocapn/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-asc) least recently updated first
  * Review [open issues](https://github.com/ocapn/ocapn/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) least recently updated first
  
  [Minutes of January meeting](https://github.com/ocapn/ocapn/pull/102) to be merged as soon as this meeting is over.

**Comment by kriskowal** [comment]
I would like to discuss locators, addresses, and references https://github.com/ocapn/ocapn/pull/105

**Comment by jar398** [comment]
Reminder that the meeting is taking place tomorrow the 13th (during a Northeast US snowstorm I think).

**Comment by zarutian** [comment]
[Meeting minutes cryptpad](https://cryptpad.fr/code/#/2/code/edit/k58qU9fAFJHi3o9zFBhAiD8t/)

**Comment by jar398** [comment]
David Thompson was scribe.  I'm happy to give you the ability to push PRs etc, just contact me to confirm your github id:  jarw3@mumble.net

**Comment by jar398** [comment]
Do we have a volunteer to create a PR for the minutes (from the cryptpad)?

**Comment by jar398** [comment]
Oops.  Done.  #106 by @tsyesika .
