### ISSUE TITLE
November 2024 Meeting

### ISSUE THREAD

**Issue by kriskowal** [ocapn/ocapn#137]
**Date/time**: 2nd Tuesday [19:00 UTC on 12 November 2024](https://www.timeanddate.com/worldclock/converter.html?iso=20241112T190000&p1=239&p2=1440&p3=43&p4=1240).
**Location**: https://bbb.sfconservancy.org/b/chr-pm5-cl8-ctl
**Scribe**: TBD 
**Preliminary agenda**:
 * [Closed issues](https://github.com/ocapn/ocapn/issues?q=is%3Aissue+is%3Aclosed)  - discussion only if there are objections
 * Status of October minutes #140 - review and approval deferred until December
 * Abstract data model #125, see below
 * Review [open issues](https://github.com/ocapn/ocapn/issues) e.g. 
     * #20
     * #24
     * #25
     * #29

Agenda:

- @kriskowal At the October meeting, we agreed to revisit the proposed Abstract Data Model if there are further questions pending @tsyesika’s return from vacation, with an expectation we would defer again if Jessica doesn’t have an opportunity to complete a review before then. https://github.com/ocapn/ocapn/pull/125

**Comment by kriskowal** [comment]
@jar398 I propose for this meeting or a future meeting a discussion on using netstring as a message framing protocol around Syrup in netlayers like TCP that would otherwise require a streaming Syrup parser https://github.com/ocapn/ocapn/issues/138

**Comment by jar398** [comment]
Minutes for October meeting are still missing.

**Comment by jar398** [comment]
Reminder: Check the meeting time - some locations have had time zone changes since our last meeting.  By my reckoning our meeting is an hour and 15 minutes away.

**Comment by zarutian** [comment]
[Cryptpad meeting minutes](https://cryptpad.fr/code/#/2/code/edit/LcnRQM9Hjo56PuN9xwrVNxH8/)

**Comment by jar398** [comment]
Minutes PR: #141
