### ISSUE TITLE
exploration: Agoric marshal types, protobuf, rholang data types

### ISSUE THREAD

**Issue by dckc** [ocapn/ocapn#19]
As @erights was presenting Agoric [marshal types](https://github.com/Agoric/agoric-sdk/blob/master/packages/marshal/src/types.js) and such in the ZEstival last week, I said it's remarkable how much it looks like the data types in [rholang](https://rholang.github.io/tutorials/cheat-sheet/): immutable lists, sets, maps, etc. as well as matching and sorting.

Based on some some type-directed prototyping ([marshal-rhoproto.js](https://gist.github.com/dckc/60caeb9c352e8e6186215735b7e719e3) in service of rchain-community/js2rho#16 , I think using [RhoTypes.proto](https://github.com/rchain/rchain/blob/dev/models/src/main/protobuf/RhoTypes.proto) for interchange is promising, though I doubt the matching and sorting semantics are consistent between Agoric and RChain in the details. I haven't tried a serializing matchers in such a way that they would show up as matchers in rholang yet. That would be a good test.

cc @cwebber @kriskowal

**Comment by zenhack** [comment]
Hm, there's a lot of stuff in `RhoTypes.proto` that probably don't make sense in language-agnostic protocol; it looks like it is designed to encode a full rho AST, not just data literals & caps.

...either way, we really should nail down the data model before we devote too may cycles to specific encodings.

**Comment by dckc** [comment]
> Hm, there's a lot of stuff in `RhoTypes.proto` that probably don't make sense in language-agnostic protocol; it looks like it is designed to encode a full rho AST, not just data literals & caps.

sure; I don't propose to use the whole thing. Just the relevant parts.

> ...either way, we really should nail down the data model before we devote too may cycles to specific encodings.

I don't know how to nail down abstract things; only running code that I can test.

**Comment by dckc** [comment]
doubt this is worth tracking going forward
