### ISSUE TITLE
The simple implementation rule: 2 parties implementable in 1 week, 3 parties in 3 weeks

### ISSUE THREAD

**Issue by cwebber** [ocapn/ocapn#2]
Observing the popularity of HTTP, JSON, and (wide-implementation-wise) bencode as rather than being the best possible protocols or representations being "good enough" and easy to implement protocols / data representations, I'd observe that we should make it a goal that a dedicated programmer, with access to a programming language with a reasonable standard library, and a library for cryptographic primitives (should those even be required), a seasoned developer should be able to implement OCapN in a single week for the simplest (2-party) cases, once we have fully defined things.

This sets several bars for us:

 - It means we have to have a very easy step-by-step implementation guide and clear documentation
 - It means that we keep OCapN conceptually simple wherever possible
 - It means the data representation library should be so simple that it take up no more than one day of that week, should the developer need to implement it from scratch

At its heart, in the simple 2-party case, CapTP really is this simple, but we haven't yet spent the time extracting the heart of its simplicity.

The 3-party case is more complex, because of two things:

1) It requires setting up the netlayer stuff, whereas 2-party can be done with the abstraction of wiring an abstracted bytestream on both ends
2) It involves some hard to grokk stuff about certificates

This is aspirational; perhaps it will not be possible.  But I'd like to keep this aspiration in place... it informs and constrains this work.  It leaves us to ask, every time, "how much might this decision deviate from the simple implementation rule?"

**Comment by cwebber** [comment]
Also: obviously this means simplicity of implementation *once we have finished defining this work*.

**Comment by dckc** [comment]
A test suite is typically the most clear documentation, IME.

**Comment by cwebber** [comment]
Yes, see issue #8 :)

But an implementation guide can make a huge difference.  I cannot imagine having implemented JSON-LD, which is considerably more complicated than CapTP, without the corresponding [processing algorithms and api](https://www.w3.org/TR/json-ld-api/) document.  It would be good to have altogether:

1. A short primer which explains the ideas
2. A specification which describes all the behavior, absent any specific implementation details
3. An implementation guide
4. A test suite

(2) and (4) are the most important.  But (1) and (2) can help a lot.

**Comment by kriskowal** [comment]
At today’s meeting, @tsyesika volunteered to document this aspiration in the README and close this issue in accordance with the agreement among participants on the call.
