### ISSUE TITLE
First pre-standardization meeting - 2022-12-06 8-9pm UTC

### ISSUE THREAD

**Issue by tsyesika** [ocapn/ocapn#23]
We're thinking kicking the first meeting off with introductions of who everyone is and  where everyone's at. We need to schedule the meeting, I've created a poll for this, please mark when you're available so we can schedule a time which works best for all who want to participate.

Poll: https://framadate.org/S7VfMGjGj2XriXeN

Note I've listed all the times in UTC since there's no support for timezones in framadate.org please ensure to convert to your local timezone using for example https://www.timeanddate.com/worldclock/converter.html

**Comment by tsyesika** [comment]
Looking at the poll, it seems Tuesday at 20:00 (8pm) to 21:00 (9pm) UTC works the best for everyone. Here's a link which should help convert it to your timezone:

https://www.timeanddate.com/worldclock/converter.html?iso=20221206T200000&p1=1440

The agenda for this meeting is:

- Introductions of everyone attending
- Meta-discussion about group, meetings, etc.
- A review of current implementations and status

**Comment by zenhack** [comment]
Quoting Christine Lemmer-Webber (2022-11-22 11:00:31)

>    We will also be doing live IRC scribing (w3c style) on #spritely on
>    irc.libera.chat

Would #ocapn make more sense?

**Comment by tsyesika** [comment]
I think using the #ocapn IRC channel makes sense.

**Comment by cwebber** [comment]
Yes `#ocapn`.  That was just a typo.

**Comment by pyrocto** [comment]
I'm unable to connect to irc.libera.chat

**Comment by zenhack** [comment]
Per the spritely discourse:

> For people wanting to talk and summaries where their implementations are at, can you mention it on the issue so can divide the time needed between everyone.

Quick summary on my end, which I can rehash day-of:

- go-capnp work is fairly active at the moment, good chance we'll get 3PH in the next few months.
  - Right now there's a window of opportunity where we can make changes to how 3PH will look in capnp, since it's not deployed, but once that's implemented it will be harder. Accordingly, I'd like to smoke out constraints here early on.
- Forgefed folks are looking at haskell-capnp, so their feedback is likely to inform development there.

**Comment by tsyesika** [comment]
There's nothing needed to do to prepare for the meeting, it'll just be an introductory meeting where we talk about who everyone is, what we want to do going forward and where all the implementations are currently at. The meetings will be kicking off in earnest in January.

**Comment by tsyesika** [comment]
The minutes from the last meeting are available for review so they can be approved at the next meeting. You can find them here: https://github.com/ocapn/ocapn/pull/26
