### ISSUE TITLE
Capabilities vs. CapTP

### ISSUE THREAD

**Issue by jfinkhaeuser** [ocapn/ocapn#25]
Reading through the README, it seems as if the notion of capabilities is tightly coupled to CapTP here, which I suppose makes sense.

I'd just like to point you to towards [draft-jfinkhaeuser-caps-for-distributed-auth](https://datatracker.ietf.org/doc/draft-jfinkhaeuser-caps-for-distributed-auth/) as an exploration of capability based authorization generalized away from CapTP. This is an informational/overview draft, not specification.

Nonetheless, as I discussed on the fedi with some of you, it may be very worthwhile for you to provide feedback. The document is managed at https://codeberg.org/interpeer/specs and I'd be happy to take pull requests for it.

**Comment by jfinkhaeuser** [comment]
After some discussion, I think it'd be possible to highlight the ocapn use case more strongly.

But it's also worth stressing that the linked doc is deliberately an abstract overview. Specific implementations could still do things in addition to this overview, or even differently. The reason to have the overview is to have something to point to that basically says "this is how cryptographic capabilities work in principle", and then talk about differences in your system.

So I'd really like some feedback from this community here!

**Comment by jar398** [comment]
Discussed in [2024 December meeting](https://github.com/ocapn/ocapn/blob/9b3466a1f8f458ea048302eddd2901968218f0e7/meeting-minutes/2024-12-10.md).  Decision was to close as unactionable.
