### ISSUE TITLE
Appointing a new chair

### ISSUE THREAD

**Issue by tsyesika** [ocapn/ocapn#27]
As I mentioned in the meeting on 2022-12-06, we should be thinking about appointing a new chair. If you'd be interested in nominating someone (including yourself) or have opinions, put them here!

**Comment by cwebber** [comment]
Horray!  First of all, I want to say that I think you did a great job chairing the first meeting @tsyesika and am happy with you as *interim* chair, even though I agree it would be better to have someone else long term. :)

I personally suggest Jonathan Rees / @jar398 for his background in ocaps, his previous standardization work being on the W3C TAG and the Scheme standardization committee, and also in his extreme thoughtfulness.

**Comment by tsyesika** [comment]
@jar398 being the new chair has been voted on and approved in the Feb 2023 meeting! I'm going to close this issue.
