### ISSUE TITLE
insufficient github access for participants

### ISSUE THREAD

**Issue by dckc** [ocapn/ocapn#31]
I'd like to assign myself to #6 .

as noted in https://github.com/ocapn/ocapn/issues/28#issuecomment-1407469846

**Comment by dckc** [comment]
Thanks, @tsyesika !

As we discussed, I can imagine a ritual where (1) folks agree to the charter and (2) they're granted collaborator access.

**Comment by dckc** [comment]
@jar398 @tsyesika would you please provide full contributor access to more or less everyone?

I suggest we should all be authorized to:

 - edit the wiki
 - tag issues
 - assign issues
 - merge PRs

everyone who has attended a meeting, for example? Perhaps getting their github logins would be tedious.

Here's a list of all commentors in this repo:

```
['zarutian', 'MostAwesomeDude', 'kriskowal', 'zenhack', 'kentonv', 'cwebber', 'erights', 'dckc', 'tsyesika', 'gobengo', 'aschrijver', 'pyrocto', 'jar398', 'jfinkhaeuser', 'ocdtrekkie', 'frandallfarmer', 'elplatt', 'gibson042', 'tgrecojs']
```

I got it from the [github graphql explorer](https://docs.github.com/en/graphql/overview/explorer) using this query:

```graphql
query { 
  repository(owner: "ocapn", name: "ocapn") {
    issues(last:100) {
      nodes {
        comments(last:100) {
          nodes {
            author {
              login
            }
          }
        }
      }
    }
  }
}
```

and then post-processed the results in a browser console:

```js
authors = { ... result from query above ... }
issues = authors.data.repository.issues.nodes
authorBag = issues.flatMap(i => i.comments.nodes.map(c => c.author.login))
uniq = a => [...new Set(a)]
uniq(authorBag)
```

**Comment by jar398** [comment]
Hoping for advice from the project owner(s) and/or someone who has managed a repo for an 'open' membership group like this one before.

**Comment by jar398** [comment]
@dckc I've upped your 'role' to 'write' while recognizing that this does not give a general solution to the problem (issue remains open).

**Comment by jar398** [comment]
Until we have a different policy, those actively participating in the group who desire write access to the repo can request it from me. If you don't know my email address already, look here: https://mumble.net/~jar/

**Comment by zenhack** [comment]
Quoting Jonathan A Rees (2023-03-30 10:58:37)

>    Until we have a different policy, those actively participating in the
>    group who desire write access to the repo can request it from me.

I would like write access.

**Comment by jar398** [comment]
@zenhack granted

**Comment by dckc** [comment]
I suppose "ask @jar398 if you want access" is a reasonable implementation of...

> (1) folks agree to the charter and (2) they're granted collaborator access.
