### ISSUE TITLE
February 2023 Meeting

### ISSUE THREAD

**Issue by tsyesika** [ocapn/ocapn#32]
Last meeting we decided to set the date of the next meeting. The following is the information:

**Date:** Thursday 23rd of February 8pm UTC - 9pm UTC (convert to your timezone: https://www.timeanddate.com/worldclock/converter.html?iso=20230223T200000&p1=1440)
**Meeting Location**:  https://bbb.sfconservancy.org/b/chr-pm5-cl8-ctl
**Scribe:** @elplatt 
**Agenda:**
- https://github.com/ocapn/ocapn/issues/27
- Announcing new website for the group [ocapn.org](https://ocapn.org)
- #29 

If someone is able to setup up as a scribe, please let me know. If people have specific items they wish to add to the agenda please let me know in the comments.

**Comment by elplatt** [comment]
@tsyesika I can scribe for this one

**Comment by tsyesika** [comment]
Thanks for offering to scribe :)

**Comment by dckc** [comment]
yes, per https://github.com/ocapn/ocapn/pull/35#issuecomment-1468386294
