### ISSUE TITLE
Prepare a set of working drafts

### ISSUE THREAD

**Issue by jar398** [ocapn/ocapn#37]
This is an issue to assist in tracking @tsyesika 's documentation work.  @tsyesika can elaborate.  I've started to collect related issues under a 'first working drafts' milestone; more can be added to the milestone if that helps. Any administrative or miscellaneous topics can be raised here in this issue.

(tbd: link to minutes of the 3/24 meeting from here)

**Comment by jar398** [comment]
I'm trying to put together an agenda for our meeting which is in less than a week.  @tsyesika are the drafts something we might be able to talk about?

**Comment by tsyesika** [comment]
Yes! I plan to publish the CapTP spec draft at the latest on Friday so there is a little time before the meeting, so it does make sense for us to talk about it at the meeting.

**Comment by tsyesika** [comment]
The draft is living on https://github.com/ocapn/ocapn/pull/42 :) Please take a look!

**Comment by jar398** [comment]
Thanks.  This issue is for an unspecified "set of working drafts".  I'm wondering when we can close it.  
1. The first draft of the main spec is out,
2. and the test suite is under review with its own issue #8.
3. According to my own notes we are also looking for one 'concrete syntax' or netlayer binding spec,
4. and a reference implementation,
5. and a spec in the style preferred by some standards body. 

I'm inclined to make separate issues for 4 and 5 as @dckc suggests, and there is no urgency, so they can be created as needed. There is a Syrup spec providing the concrete syntax of a sample netlayer (I'm not clear on how the choice of netlayer is negotiated, but that's OK, it will be addressed some day or maybe I missed it), so it doesn't need its own issue.  If we want to make issues for future versions of the main spec we can do that, but we might just have lots of smaller issues.

So I'm going to propose closing this issue (and will do so in a day or two if there are no objections).
