### ISSUE TITLE
Recurring monthly meeting time

### ISSUE THREAD

**Issue by cwebber** [ocapn/ocapn#45]
The meetings so far have been good!  We don't have a "regular" meeting time though and I know it is preventing a few people from attending because they don't know how to schedule around them.

Allow me to suggest: fourth Tuesday of the month at 19:00 UTC.  Just throwing that out there because it's kind of close to the time we've been doing the last few times.  Other times welcome.

**Comment by zenhack** [comment]
That will work for me, and I can also make it work once we switch back to standard time.

**Comment by cwebber** [comment]
> That's OK with me but will anyone have conflicts in the fall if we don't track daylight savings time?

It does seem that the majority of the group prefers it, so yes, let's track DST.

**Comment by zenhack** [comment]
So shall we specify it as 3:00 PM US/Eastern then, to account for DST?

**Comment by tsyesika** [comment]
While my timezone does track DST, I'd prefer not to track it as DST does not happen at the same time everywhere and it can be confusing while some countries are observing a shift and others not. Not a strong preference, but just to share my preference.

I'd like to propose the 2nd Tuesday of every month instead. The 4th Tuesday would run into conflicts with both Christmas (26th of December this year) and around the time of midsummer (large holiday in Sweden).

**Comment by dckc** [comment]
from #43 / #59:
> **Decision:** 19:00 UTC on 2nd Tuesdays of the month.
