### ISSUE TITLE
Basic writeup of the current captp protocol

### ISSUE THREAD

**Issue by cwebber** [ocapn/ocapn#7]

**Comment by zarutian** [comment]
hmm
```ebnf
protocol_msgs := protocol_msg [ protocol_msgs ]
```
(this comments will be undergoing lot of edits)

**Comment by zarutian** [comment]
The last post has EBNF of the current captp protocol as I understand it.

**Comment by dckc** [comment]
@jar398 @tsyesika I suggest using this issue for the "main document is document specifying CapTP". Tweak the title / description as appropriate.

**Comment by dckc** [comment]
see also #42

**Comment by dckc** [comment]
fixed in #42 ? #60 seems to be in progress.

**Comment by tsyesika** [comment]
Closing as we have the draft specifications.
