### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by cwebber** [ocapn/ocapn#8]

**Comment by dckc** [comment]
@tsyesika seems to have the ball on this, per next week's agenda (#43).

Ah... and I see some tangible progress: https://github.com/ocapn/ocapn-test-suite e074a22

Here's hoping for time to take a closer look.

cc @kriskowal

**Comment by jar398** [comment]
At the 5/23 meeting, @zenhack volunteered to review, so I'm adding him as an assignee to this issue

**Comment by tsyesika** [comment]
I'm wondering if we should close this given the test suite has been written and is available here: https://github.com/ocapn/ocapn-test-suite WDYT?

**Comment by dckc** [comment]
concur.

Without a description, it's a little difficult to provide evidence that a critical mass of participants agree with this resolution, but given our subject-to-appeal-at-next-meeting process, I think it's reasonable to close this.

for referece: it's currently [4242a7b](https://github.com/ocapn/ocapn-test-suite/commit/4242a7b096ac3a69adca8d8cf4a98c010b3fc694)
